# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Skylabs NZ Blog
# Description of the Site
description: Stargazing, Astrophotography, Astronomy, Night Photography
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Stargazing, Astrophotography, Astronomy, Night Photography
# URL for the Image of custom Favicon
favicon-url: http://skylabs.co.nz/images/favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: http://skylabs.co.nz/images/banner.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: skylabsnz@gmail.com
facebook_username: skylabs.co.nz
instagram_username: skylabsnz
github_username:  skylabs.co.nz
youtube_channel_id: UCKD6GHCrqgmhSXcICPtu7Iw

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: skylabs.co.nz

# Name of the Author
author-name: Jordi Blasco
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about:[Jordi Blasco](https://www.linkedin.com/in/jordiblascopallares/) started to get interested in astronomy since he was a young kid. He has been a very active astronomy advocate and science communicator for the general public. He has been vice-president of Galileo, the astronomical society of the University of Barcelona from 1999 to 2005. Jordi has a licentiate degree (BSc + MSc) in physics with specialisation in computational physics from University of Barcelona (Spain). He is CTO & co-founder of <a href="http://hpcnow.com"><b>HPCNow!</b></a>, a global consulting company focused in High Performance Computing, High Performance Data Analytics, Machine Learning and Artificial Intelligence. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
